### ISSUE TITLE
JR instruction is not handled correctly in z80asm assembler. Affects retro.asm

### ISSUE THREAD

**Issue by dennowiggle** [johnwinans/2063-Z80-cpm#20]
The z80asm assembler used in the Z80 Retro project does not detect out of range jumps. The issue shows up on line 299 in retro.asm.
```jr    nz,.wboot_loop        ; if BC != 0 then goto .wboot_loop```

**Comment by johnwinans** [comment]
I appreciate that the target address range of a relative jump is limited.  But I am confused as to why there is a problem with the following code.  The target is 0x50 bytes away and the range is up to 0x7F

```
eb38 b7                         or      a                       ; disk_read sets A=0 on success 
eb39 28 50                      jr      z,.wboot_sec_ok         ; if read was OK, continue processing 
eb3b                     
eb3b                            ; If there was a read error, stop. 
eb3b cd 9b f5                   call    iputs 
eb3e ..                         db      "\r\n\r\nERROR: WBOOT READ FAILED.  HALTING." 
eb65 ..                         db      "\r\n\n*** PRESS RESET TO REBOOT ***\r\n" 
eb87 00                         db      0 
eb88 c3 88 eb                   jp      $                       ; endless spin loop 
eb8b                     
eb8b                    .wboot_sec_ok: 
```

**Comment by dennowiggle** [comment]
My bad sorry. I rechecked and the listing output is fine with a jump of -128 which is correct for the .wboot_loop label.
```ebac 20 80			jr	nz,.wboot_loop		; if BC != 0 then goto .wboot_loop ```

The z80asm for the Z80 project is fine and DOES provide warnings for out of range jumps. I was was playing with 3 or 4 assemblers yesterday and got my wires crossed.

**Comment by dennowiggle** [comment]
This is a non-issue, so closing.
