### ISSUE TITLE
Change "call bios_debug_disk" to "call disk_dump"

### ISSUE THREAD

**Issue by dennowiggle** [johnwinans/2063-Z80-cpm#21]
In order to use disk debug features in disk_nocahe.asm and disk_dmcache.asm the call to "bios_debug_disk" should be changed to call "disk_dump". The function that is called must have changed names at some point.

**Comment by johnwinans** [comment]
Sorry this slipped through the cracks.  I will clean this up.  Thanks.

**Comment by johnwinans** [comment]
Done!
