### ISSUE TITLE
Makefiles use non-portable constructs

### ISSUE THREAD

**Issue by thorpej** [johnwinans/2063-Z80-cpm#22]
The Makefiles in this repository use some non-portable constructs.  For example, "date --rfc-3339=seconds" is a GNU extension that's not available on other platforms, such as BSD and macOS.  This issue tracks replacing those non-portable constructs with equivalent (or nearly-equivalent) ones that are available on more systems.

**Comment by thorpej** [comment]
I'm working on a patch for this issue.

**Comment by johnwinans** [comment]
FYI - I manually added this to the dev branch.
