### ISSUE TITLE
Unable to clone cpm submodule

### ISSUE THREAD

**Issue by ewe2** [johnwinans/2063-Z80-cpm#6]
Problem:

Cloning submodules with the git@github.com form forces publickey signatures which fails. You probably meant to use https form.

Solution:

Edit .gitmodules to change 

git@github.com:Z80-Retro/cpm-2.2.git 

to read 

https://github.com/Z80-Retro/cpm-2.2.git 

(note NOT the " : " ) 

I have tested the https form with a clone and this works.

Users will have to regenerate the download to be sure the toplevel .git/config does not include the old config.

**Comment by johnwinans** [comment]
Good call.  I often mess this up.
Thanks.
